# Generated by Django 4.1.1 on 2022-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.FloatField(blank=True, null=True)),
                ('dato2', models.CharField(max_length=10)),
                ('dato3', models.FloatField(blank=True, null=True)),
                ('dato4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
